### ISSUE TITLE
Investigate RPS Issues on Production

### ISSUE THREAD

**Issue by danwbyrne** [neotracker/neotracker#152] opened 2020-04-20 22:20 UTC
### Description

Our production cluster consistently has issues under any reasonable amount of load. 

<img width="1321" alt="Screen Shot 2020-04-20 at 3 12 06 PM" src="https://user-images.githubusercontent.com/9561608/79804917-d89fe500-8319-11ea-8f0b-1606c8d02449.png">

![image](https://user-images.githubusercontent.com/9561608/79804791-970f3a00-8319-11ea-8fcb-49194d50de58.png)

When our cluster reaches ~12+ RPS it becomes unhealthy and will 502. This is *incredibly* low, each webserver should be able to handle 50-100+ RPS without crashing and we are running *SIX*. 

Compare this to our staging cluster during a siege test running 1 webserver:

<img width="1317" alt="Screen Shot 2020-04-20 at 3 11 38 PM" src="https://user-images.githubusercontent.com/9561608/79804949-ece3e200-8319-11ea-98a7-ddd3183ac660.png">

handles 40 RPS without going down.

**Expected behavior:** It should be able to handle at least 6*40 = 240 RPS

**Actual behavior:** becomes unhealthy at ~13 RPS

### Additional Information

The only difference between staging and production is `neg` settings which will take down the ingress for a time. I am going to try making this change during low traffic hours.

This issue HAS to be resolved before we deploy moonpay to production if we expect that to have any affect on our traffic load.

**Comment by spencercorwin** [comment] 2020-05-14 02:49
Duplicate of #169

**Closed by spencercorwin** 2020-05-14 02:49 UTC
Labels: P1, help wanted
